title: Infinityheroes Documentation
description: The offical Documentation of ifheroes.de
theme: just-the-docs
source: docs
logo: "/assets/images/1Scdall-e-2024-05-20-20-00-02-create-an-infinity-icon-in-yellow-designed-in-the-style-of-minecraft-removebg-preview.png"

url: https://just-the-docs.github.io

aux_links:
  Website: https://ifheroes.de
